'use strict';

// Read in a file from the command line containing tz json data
// generated by https://github.com/mde/timezone-js.
// Turn this into a friendly format for displaying in a HTML select box.
var fs = require('fs');

var tzDataFile = process.argv[2] || 'tz.json';
var tzData = JSON.parse(fs.readFileSync(tzDataFile));

var result = Object
  .keys(tzData.zones)
  .sort()
  .map(function(city) {
    var rtn = {
      value: city
    };
    var parts = city.split('/');
    if(parts.length > 1) {
      rtn.region = parts[0] !== 'Etc' ? parts[0] : 'Other';
      rtn.label = parts.reduce(function(soFar, part, i) {
        if(i > 0) {
          soFar.push(part.replace(/_/g, ' '));
        }
        return soFar;
      }, []).join(' - ');
    } else {
      rtn.region = 'Other';
      rtn.label = parts[0].replace(/_/g, ' ');
    }

    return rtn;
  })
  .sort(function(a, b) {
    if(a.region === b.region) {
      if(a.label < b.label) { return -1; }
      if(a.label > b.label) { return 1; }
      return 0;
    }

    if((a.region !== 'Other' && b.region !== 'Other') ||
       (a.region === 'Other' && b.region === 'Other')) {
      if(a.region < b.region) { return -1; }
      if(a.region > b.region) { return 1; }
      return 0;
    }

    if(a.region === 'Other') { return 1; }
    if(b.region === 'Other') { return -1; }
    return 0;
  });

console.log(JSON.stringify(result, null, 2));
